language: php

sudo: false

php:
    - 7.1
    - 7.2

env:
    - WP_VERSION=latest
    - WP_VERSION=4.9.7

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "phpunit/phpunit=5.7.*"

  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
