language: php

sudo: false

php:
    - 5.6
    - 7.0
    - 7.1

env:
    - WP_VERSION=nightly
    - WP_VERSION=latest
    - WP_VERSION=4.7
    - WP_VERSION=4.6

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "phpunit/phpunit=5.7.*"

  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
